### ISSUE TITLE
Read contents in build dir

### ISSUE THREAD

**Issue by zslabs** [superwolff/metalsmith-fingerprint-ignore#3]
Hi alll,
I'm using Metalsmith along with Gulp to build my site. Instead of having Metalsmith handle my assets, I have several Gulp tasks that put these in the build directory before processing my pages. So what I'm trying to do is have this package read those contents like so:

```
.use(fingerprint({
  pattern: '../dist/assets/css/site.css'
}))
```

I'm using `process.cwd()` with my Metalsmith install, but relative paths don't seem to be working to grab a file outside of the `src/` directory. Any tips on how to reach those built files? Thanks!

**Comment by ismay** [comment]
Hi,

This plugin will only process files from the source dir (as those are the files that metalsmith processes and passes to this plugin). The pattern option merely filters those files (for when you only want to fingerprint `*.css` for example).

So if you want to fingerprint files with this plugin you'll need to put them in the source dir.
